name: Topic 8 Project
on: push
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: website scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0-9.0
        with:
          target: https://juice-shop.herokuapp.com/#/search
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'